import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "bsds")
public class Data {

    private String id;
    private String key;
    private String val;

    public Data() {
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "word")
    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    @DynamoDBAttribute(attributeName = "val")
    public String getVal() {
        return val;
    }

    public void setVal(String val) {
        this.val = val;
    }
}